### ISSUE TITLE
decoding MultiPolygon

### ISSUE THREAD

**Issue by jxs** [bryanjos/geo#11]
Hi there, i am having errors decoding MultiPolygon, either with ecto 
```
iex(11)> Transfere.Repo.all(query)                                                                                                                              [debug] SELECT l0."id", l0."freguesia", l0."municipio", l0."distrito", l0."geom" FROM "locations" AS l0 LIMIT 5 (1.1ms)
** (ArgumentError) cannot load `"0106000020E6100000010000000103000000010000000F00000091A1EF7505D521C0F4AD6182E481424072B3CE92FED421C01D483CDAE281424085184FAEF7D421C0CB159111E1814240E1EBD7FBF8D421C0D421F7C8DF814240AD111315FFD421C0FE1F21C0DE81424082A0669908D521C050071118DE814240813C5E700FD521C0954EEF97DE814240DC889FA815D521C0B3382182E08142400148A81817D521C0E620D22BE2814240F1E95BDE19D521C08BD53852E3814240F81699E217D521C05B35D7DCE4814240B287C8D715D521C0336338FEE481424085882FB90FD521C0FEF65484E5814240A53E1E460AD521C09A0EA286E581424091A1EF7505D521C0F4AD6182E4814240"` as type Geo.MultiPolygon
             lib/ecto/type.ex:315: Ecto.Type.load!/2
             lib/ecto/schema.ex:553: anonymous fn/3 in Ecto.Schema.do_load/4
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
             lib/ecto/schema.ex:551: Ecto.Schema.do_load/4
             lib/ecto/schema.ex:545: Ecto.Schema.__load__/4
             lib/ecto/adapters/sql.ex:403: anonymous fn/3 in Ecto.Adapters.SQL.process_row/2
    (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
             lib/ecto/adapters/sql.ex:396: Ecto.Adapters.SQL.process_row/2
```
and with Geo.WKB.decode

``` 

iex(11)> Geo.WKB.decode("0106000020E6100000010000000103000000010000000F00000091A1EF7505D521C0F4AD6182E481424072B3CE92FED421C01D483CDAE281424085184FAEF7D421C0CB159111E1814240E1EBD7FBF8D421C0D421F7C8DF814240AD111315FFD421C0FE1F21C0DE81424082A0669908D521C050071118DE814240813C5E700FD521C0954EEF97DE814240DC889FA815D521C0B3382182E08142400148A81817D521C0E620D22BE2814240F1E95BDE19D521C08BD53852E3814240F81699E217D521C05B35D7DCE4814240B287C8D715D521C0336338FEE481424085882FB90FD521C0FEF65484E5814240A53E1E460AD521C09A0EA286E581424091A1EF7505D521C0F4AD6182E4814240")
** (Protocol.UndefinedError) protocol Enumerable not implemented for %Geo.Polygon{coordinates: [[{-8.91605728674111, 37.014786050505705}, {-8.916004741413165, 37.01473548835222}, {-8.915952155261275, 37.014681049196575}, {-8.915962095363229, 37.014641876859656}, {-8.916008623674168, 37.01461030595236}, {-8.916081231858929, 37.01459027129624}, {-8.91613341474863, 37.01460551438246}, {-8.91618086764759, 37.0146639501776}, {-8.916191835920474, 37.01471469650441}, {-8.91621298667903, 37.01474979186158}, {-8.916197854221068, 37.01479683407043}, {-8.916182273129241, 37.01480081322952}, {-8.916135584881212, 37.01481680058167}, {-8.916094008628827, 37.01481707489911}, {-8.91605728674111, 37.014786050505705}]], srid: nil}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/enum.ex:981: Enum.map/2
             lib/geo/wkb.ex:239: Geo.WKB.decode_coordinates/2
             lib/geo/wkb.ex:171: Geo.WKB.decode/2
```

thanks for the lib :)

**Comment by bryanjos** [comment]
Thanks for letting me know. I've committed the fix and updated the hex version as well to 0.11.1

**Comment by jxs** [comment]
`Geo.WKB.decode` works now :) , but still having troubles querying from the MultiPolygon field

```
query = from location in Locations, limit: 5, select: location
iex(7)> Transfere.Repo.all(query)                                                                                                                               [debug] SELECT l0."id", l0."freguesia", l0."municipio", l0."distrito", l0."geom" FROM "locations" AS l0 LIMIT 5 (1.0ms)                                         ** (ArgumentError) cannot load `"0106000020E6100000010000000103000000010000000F00000091A1EF7505D521C0F4AD6182E481424072B3CE92FED421C01D483CDAE281424085184FAEF7D421C0CB159111E1814240E1EBD7FBF8D421C0D421F7C8DF814240AD111315FFD421C0FE1F21C0DE81424082A0669908D521C050071118DE814240813C5E700FD521C0954EEF97DE814240DC889FA815D521C0B3382182E08142400148A81817D521C0E620D22BE2814240F1E95BDE19D521C08BD53852E3814240F81699E217D521C05B35D7DCE4814240B287C8D715D521C0336338FEE481424085882FB90FD521C0FEF65484E5814240A53E1E460AD521C09A0EA286E581424091A1EF7505D521C0F4AD6182E4814240"` as type Geo.MultiPolygon
             lib/ecto/type.ex:315: Ecto.Type.load!/2
             lib/ecto/schema.ex:553: anonymous fn/3 in Ecto.Schema.do_load/4
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
             lib/ecto/schema.ex:551: Ecto.Schema.do_load/4
             lib/ecto/schema.ex:545: Ecto.Schema.__load__/4
             lib/ecto/adapters/sql.ex:403: anonymous fn/3 in Ecto.Adapters.SQL.process_row/2
    (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
             lib/ecto/adapters/sql.ex:396: Ecto.Adapters.SQL.process_row/2
```

on the Location model, i have:

```
defmodule Transfere.Models.Location do
  use Ecto.Model

  schema "locations" do
    field :freguesia, :string
    field :municipio, :string
    field :distrito, :string
    field :geom, Geo.MultiPolygon
    has_many :ads, Transfere.Models.Ad
  end

end
 
```

thanks

**Comment by bryanjos** [comment]
Sorry, I'll have to look into that one tonight when I get a bit more time. Looks like it's not calling the wkb decode function somewhere.

**Comment by bryanjos** [comment]
It seems I didn't correctly fix the previous issue. I have resolved it for real this time and updated the version in hex to 0.11.2.

**Comment by jxs** [comment]
sorry, still having the same error with 0.11.2
```
iex(3)> query = from location in Location, limit: 5, select: location
#Ecto.Query<from l in Transfere.Models.Location, limit: 5, select: l>
iex(4)> Transfere.Repo.all(query)
[debug] SELECT l0."id", l0."freguesia", l0."municipio", l0."distrito", l0."geom" FROM "locations" AS l0 LIMIT 5 [] (53.7ms)
** (ArgumentError) cannot load `"0106000020E6100000010000000103000000010000000F00000091A1EF7505D521C0F4AD6182E481424072B3CE92FED421C01D483CDAE281424085184FAEF7D421C0CB159111E1814240E1EBD7FBF8D421C0D421F7C8DF814240AD111315FFD421C0FE1F21C0DE81424082A0669908D521C050071118DE814240813C5E700FD521C0954EEF97DE814240DC889FA815D521C0B3382182E08142400148A81817D521C0E620D22BE2814240F1E95BDE19D521C08BD53852E3814240F81699E217D521C05B35D7DCE4814240B287C8D715D521C0336338FEE481424085882FB90FD521C0FEF65484E5814240A53E1E460AD521C09A0EA286E581424091A1EF7505D521C0F4AD6182E4814240"` as type Geo.MultiPolygon
             lib/ecto/type.ex:357: Ecto.Type.load!/2
             lib/ecto/schema.ex:553: anonymous fn/3 in Ecto.Schema.do_load/4
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
             lib/ecto/schema.ex:551: Ecto.Schema.do_load/4
             lib/ecto/schema.ex:545: Ecto.Schema.__load__/4
             lib/ecto/adapters/sql.ex:403: anonymous fn/3 in Ecto.Adapters.SQL.process_row/2
    (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
             lib/ecto/adapters/sql.ex:396: Ecto.Adapters.SQL.process_row/2
```

**Comment by bryanjos** [comment]
That's weird. I'll check it in a test project and see if I get the same result. I wrote a test for this exact case in tests/geo/ecto_test.exs and thought I resolved it.

**Comment by bryanjos** [comment]
I created a test project using the geo 0.11.2, ecto 0.8.1, and postgrex 0.7.0, created some models, one with a Geo.MultiPolygon column, ran some tests where I create a Geo.MultiPolygon from the WKB string given, insert the model into the database and ran a query exactly like the one given and I wasn't able to reproduce the issue. I'll keep trying to see if I can break it and see if I can come up with different results.

**Comment by jxs** [comment]
yeah, if i run the tests, they pass, but on the project i am using geo, i am also not able to encode and insert into the db, very weird, i am going to look into it
```
iex(5)> location = Transfere.Repo.insert(%Location{municipio: "hello", geom: geom})
[debug] INSERT INTO "locations" ("distrito", "freguesia", "geom", "municipio") VALUES ($1, $2, $3, $4) RETURNING "id" [nil, nil, %Geo.MultiPolygon{coordinates: [[[{-8.91605728674111, 37.014786050505705}, {-8.916004741413165, 37.01473548835222}, {-8.915952155261275, 37.014681049196575}, {-8.915962095363229, 37.014641876859656}, {-8.916008623674168, 37.01461030595236}, {-8.916081231858929, 37.01459027129624}, {-8.91613341474863, 37.01460551438246}, {-8.91618086764759, 37.0146639501776}, {-8.916191835920474, 37.01471469650441}, {-8.91621298667903, 37.01474979186158}, {-8.916197854221068, 37.01479683407043}, {-8.916182273129241, 37.01480081322952}, {-8.916135584881212, 37.01481680058167}, {-8.916094008628827, 37.01481707489911}, {-8.91605728674111, 37.014786050505705}]]], srid: 4326}, "hello"] (7.7ms)
** (Postgrex.Error) unable to encode value `%Geo.MultiPolygon{coordinates: [[[{-8.91605728674111, 37.014786050505705}, {-8.916004741413165, 37.01473548835222}, {-8.915952155261275, 37.014681049196575}, {-8.915962095363229, 37.014641876859656}, {-8.916008623674168, 37.01461030595236}, {-8.916081231858929, 37.01459027129624}, {-8.91613341474863, 37.01460551438246}, {-8.91618086764759, 37.0146639501776}, {-8.916191835920474, 37.01471469650441}, {-8.91621298667903, 37.01474979186158}, {-8.916197854221068, 37.01479683407043}, {-8.916182273129241, 37.01480081322952}, {-8.916135584881212, 37.01481680058167}, {-8.916094008628827, 37.01481707489911}, {-8.91605728674111, 37.014786050505705}]]], srid: 4326}` as type geometry
                lib/ecto/adapters/sql/worker.ex:26: Ecto.Adapters.SQL.Worker.query!/4
                lib/ecto/adapters/sql.ex:186: Ecto.Adapters.SQL.use_worker/3
    (transfere) web/models/repo.ex:2: Transfere.Repo.log/2
                lib/ecto/adapters/sql.ex:375: Ecto.Adapters.SQL.model/4
                lib/ecto/repo/model.ex:29: anonymous fn/8 in Ecto.Repo.Model.insert/4

```

thanks a lot for your support

**Comment by jxs** [comment]
seen the problem!
I was configuring the encoder decoder and formatter in the wrong place (in the repo module instead of config.ex)

thanks :)

**Comment by bryanjos** [comment]
Glad it works now!
