### ISSUE TITLE
Issue parsing geometry

### ISSUE THREAD

**Issue by callmeahab** [bryanjos/geo#89]
I'm getting no match error querying geometry with geo_postgis.
```
** (MatchError) no match of right hand side value: <<127, 248, 0, 0, 0, 0, 0, 0>>
    (geo) lib/geo/utils.ex:35: Geo.Utils.hex_to_float/1
    (geo) lib/geo/wkb/decoder.ex:86: Geo.WKB.Decoder.decode_coordinates/2
    (geo) lib/geo/wkb/decoder.ex:50: Geo.WKB.Decoder.decode!/2
    (qsi_search_service) deps/postgrex/lib/postgrex/type_module.ex:75: QsiSearchService.PostgresTypes."Elixir.Geo.PostGIS.Extension"/6
    (postgrex) lib/postgrex/protocol.ex:2704: Postgrex.Protocol.rows_recv/4
    (postgrex) lib/postgrex/protocol.ex:1744: Postgrex.Protocol.recv_execute/5
    (postgrex) lib/postgrex/protocol.ex:1638: Postgrex.Protocol.bind_execute/4
    (db_connection) lib/db_connection.ex:1571: DBConnection.handle/6
    (db_connection) lib/db_connection.ex:1722: DBConnection.run_prepare_execute/6
    (db_connection) lib/db_connection.ex:1834: DBConnection.run/6
    (db_connection) lib/db_connection.ex:673: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:68: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:289: Ecto.Adapters.SQL.sql_call/5
    (ecto) lib/ecto/adapters/sql.ex:479: Ecto.Adapters.SQL.execute_and_cache/6
    (ecto) lib/ecto/adapters/sql.ex:456: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
```

I tried debugging and found that the following hex was causing the error: `"7FF8000000000000"`

I also wrapped that part of code with try catch block, and it to be working but the query is too slow: https://github.com/callmeahab/geo/blob/master/lib/geo/utils.ex#L41

Any suggestions on how to fix this issue?

**Comment by bryanjos** [comment]
@callmeahab sorry I'm just getting around to responding. Have you found out on your own the solution? If not, what of geometry is specifically causing the issue?

**Comment by callmeahab** [comment]
@bryanjos This started happening to me after I did some upgrade (geo, ecto, postgrex), it was a while ago so I don't exactly remember though.

I just reverted package updates and it kept working, however what I remember was that the geometry that was causing the issue was invalid.
